### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by cgore**
Bumping everything but httpmime to the most current.
There's a test failure with the most current version of httpmime that I'll need to look into.

### CODE REVIEW

**Comment by glenjamin** [comment]
Looks like the httpmime change is on the same branch.

Do you want to remove that commit, or shall we leave this until the failure is tracked down?

**Comment by cgore** [comment]
httpmime 4.5.1 works, but 4.5.2 doesn't.
Almost all the way to current seems better to me, 4.3 -> 4.5.1.
And then later sometime somebody (possibly/probably? me) can look at the issue with 4.5.1 -> 4.5.2.

**Comment by glenjamin** [comment]
The travis build has failed. It looks like it might just be on an old clojure version - if that's it then we can just drop it out of the test suite

**Comment by cgore** [comment]
Yeah, it was just the really old Clojure 1.3 and 1.4.
I overrode the versions of the two problem libraries for that Clojure version.

**Pull request merged**
