### PR TITLE
Fix cookie jar to not partition by port

### LINKED ISSUE #51: Bug: cookies not matched when mixing urls with explicit and implicit ports
**version**

peridot/peridot 0.5.1

**problem**

When mixing urls with explicits and implicits ports (e.g. `http://foo.com` vs `http://foo.com:80`) cookies don't get matched, in a browser (Chrome) this does happen.

**repro**

See test below

**expected behavior**

I'm not 100% sure. In Chrome the cookies are matched correctly. If http without port always means port 80 (I think it does) and https without port always means port 443 (I think it does), this matching should work.

Below is a failing test, that should succeed IMO.

```clojure
(require '[ring.middleware.cookies :as cookies])

(deftest default-ports
  (let [app (cookies/wrap-cookies (fn [request] {:cookies {"counter" {:value 1}}
                                                :status 200 :body (get (:cookies request)
                                                                       "counter"
                                                                       "0")}))]
    (-> (session app)
        (request "http://hello.com")
        (doto
            (#(is (= (get (:headers (:request %)) "cookie")
                     nil)
                  "cookies are not initialized")))
        
        (request "http://hello.com")
        (doto
            (#(is (= (get (:headers (:request %)) "cookie")
                     "counter=1")
                  "cookies are recognized")))
        
        (request "http://hello.com:80")
        (doto
            (#(is (= (get (:headers (:request %)) "cookie")
                     "counter=1")
                  "cookies are also recognized when redundant port 80 is added")))
        
        (request "http://hello.com:80")
        (doto
            (#(is (= (get (:headers (:request %)) "cookie")
                     "counter=1")
                  "cookies are recognized the second time"))))



    (-> (session app)
        (request "https://hello.com")
        (doto
            (#(is (= (get (:headers (:request %)) "cookie")
                     nil)
                  "cookies are not initialized")))
        
        (request "https://hello.com")
        (doto
            (#(is (= (get (:headers (:request %)) "cookie")
                     "counter=1")
                  "cookies are recognized")))
        
        (request "https://hello.com:443")
        (doto
            (#(is (= (get (:headers (:request %)) "cookie")
                     "counter=1")
                  "cookies are also recognized when redundant port 443 is added")))
        
        (request "https://hello.com:443")
        (doto
            (#(is (= (get (:headers (:request %)) "cookie")
                     "counter=1")
                  "cookies are recognized the second time"))))))
```

### PR DESCRIPTION
**Pull request by danielcompton**
HTTP cookies are shared across all ports on a host. Previously our
cookie jar would treat cookies set from the same host on different ports
separately. Now they are all handled the same.

https://stackoverflow.com/a/16328399

Fixes #51

@jeroenvandijk, could you take a look at this and let me know if it works for you?

### CODE REVIEW

**Comment by jeroenvandijk** [comment]
@danielcompton Apologies for the delayed response. Herewith I can confirm it fixes my scenario that was failing before! Thank you!

Btw, I've added a `deps.edn` file [1] to test this branch . It's not complete, but for this purpose it is enough. Do you want a PR for this?

[1] https://github.com/jeroenvandijk/peridot/commit/2b9a3a93961942328c7f58778d2862810f7f7989

**Comment by danielcompton** [comment]
>  It's not complete, but for this purpose it is enough. Do you want a PR for this?

Sure!

**Comment by Frozenlock** [comment]
Thank you for this fix, it was really needed to complete my tests!

Would it be possible to push a new release shortly?

**Comment by danielcompton** [comment]
Done as 0.5.4!

**Pull request merged**
